### ISSUE TITLE
clang: error: no such file or directory: 'NOTFOUND'

### ISSUE THREAD

**Issue by dannygosain1** [alliedel/anomalyframework_python#1]
I am trying to run 'runscript.py' with my own .train file. This is the script I'm running:

```
infile_features_libsvm = '/Users/dannygosain/workspace/URA/trainFiles/first_run.train'
lambd = 1000.0
if not os.path.isfile(infile_features_libsvm):
    print('Creating the .train file for {}'.format(infile_features))
    X = np.load(infile_features)
    liblinear_utils.write(X, y=None, outfile=infile_features_libsvm, zero_based=True)

# Run anomaly detection
a, pars = run.main(infile_features=infile_features_libsvm, n_shuffles=10, lambd=lambd)
```

Output:
```
2018-04-06 14:05:02,602 - root - INFO - Building project files
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dannygosain/workspace/anomalyframework_python/build
clang: error: no such file or directory: 'NOTFOUND'
clang: error: no such file or directory: 'NOTFOUND'
make[2]: *** [anomalyframework/cpp/multicore-liblinear/CMakeFiles/multicore-liblinear.dir/linear.cpp.o] Error 1
make[1]: *** [anomalyframework/cpp/multicore-liblinear/CMakeFiles/multicore-liblinear.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "runscript.py", line 52, in <module>
    a, pars = run.main(infile_features=infile_features_libsvm, n_shuffles=10, lambd=lambd)
  File "/Users/dannygosain/workspace/anomalyframework_python/anomalyframework/run.py", line 23, in main
    subprocess.check_output('make')
  File "/Users/dannygosain/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/dannygosain/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.
v1020-wn-230-46:anomalyframework_python dannygosain$ cd build/
v1020-wn-230-46:build dannygosain$ make
[  6%] Building CXX object anomalyframework/cpp/multicore-liblinear/CMakeFiles/multicore-liblinear.dir/linear.cpp.o
clang: error: no such file or directory: 'NOTFOUND'
clang: error: no such file or directory: 'NOTFOUND'
make[2]: *** [anomalyframework/cpp/multicore-liblinear/CMakeFiles/multicore-liblinear.dir/linear.cpp.o] Error 1
make[1]: *** [anomalyframework/cpp/multicore-liblinear/CMakeFiles/multicore-liblinear.dir/all] Error 2
make: *** [all] Error 2
```

Cmake seems to be looking for linear.cpp.o but cannot find it.

Your help is appreciated.

**Comment by mayank18garg** [comment]
hey, i'm trying to run the code demo.py.
but there is no file named 'local_pyutils'.
Please help me asap, @dannygosain1 @alliedel
